# Generated by Django 4.2.23 on 2025-07-27 21:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Naziv (ime tvrtke ili osobe)')),
                ('address', models.TextField(verbose_name='Adresa')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Unesite ispravan email format.', regex='^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$')], verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Dobavljač?')),
                ('oib', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_oib', message='OIB mora imati točno 11 znamenki.', regex='^\\d{11}$')], verbose_name='OIB')),
                ('country', models.CharField(default='Hrvatska', max_length=100, verbose_name='Država')),
                ('city', models.CharField(max_length=100, verbose_name='Grad')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Poštanski broj')),
                ('county', models.CharField(blank=True, max_length=100, null=True, verbose_name='Županija')),
                ('long_term_relationship', models.BooleanField(default=False, verbose_name='Dugoročni odnos')),
                ('relationship_status', models.CharField(choices=[('active', 'Aktivan'), ('inactive', 'Neaktivan'), ('prospective', 'Potencijalni'), ('former', 'Bivši'), ('blocked', 'Blokiran')], default='active', max_length=20, verbose_name='Status odnosa')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Datum kreiranja')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Datum ažuriranja')),
                ('tenant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclients', to='client.clientsupplier', verbose_name='Tenant (Holding/Operativa)')),
            ],
            options={
                'verbose_name': 'Klijent/Dobavljač',
                'verbose_name_plural': 'Klijenti/Dobavljači',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20, verbose_name='Razina lojalnosti')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Povratne informacije')),
                ('post_sales_feedback', models.TextField(blank=True, null=True, verbose_name='Post-prodajne povratne informacije')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clientprofile', to='client.clientsupplier')),
            ],
            options={
                'verbose_name': 'Profil klijenta',
                'verbose_name_plural': 'Profili klijenata',
            },
        ),
        migrations.CreateModel(
            name='ClientActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(verbose_name='Activity Description')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('activity_type', models.CharField(choices=[('create', 'Kreiranje'), ('update', 'Ažuriranje'), ('delete', 'Brisanje'), ('status_change', 'Promjena statusa'), ('other', 'Ostalo')], default='other', max_length=20, verbose_name='Tip aktivnosti')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='client.clientsupplier', verbose_name='Klijent/Dobavljač')),
            ],
            options={
                'verbose_name': 'Log aktivnosti',
                'verbose_name_plural': 'Logovi aktivnosti',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CityPostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5}$')], verbose_name='Postal Code')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Naselje')),
                ('county', models.CharField(blank=True, max_length=100, null=True, verbose_name='Županija')),
            ],
            options={
                'verbose_name': 'Poštanski broj',
                'verbose_name_plural': 'Poštanski brojevi',
                'indexes': [models.Index(fields=['postal_code'], name='client_city_postal__bddf1a_idx'), models.Index(fields=['city'], name='client_city_city_77cf8f_idx')],
                'unique_together': {('postal_code', 'city')},
            },
        ),
        migrations.AddIndex(
            model_name='clientsupplier',
            index=models.Index(fields=['name', 'email'], name='client_clie_name_fe02e2_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsupplier',
            index=models.Index(fields=['oib'], name='client_clie_oib_5d8873_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsupplier',
            index=models.Index(fields=['relationship_status', 'is_active'], name='client_clie_relatio_704cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='clientactivitylog',
            index=models.Index(fields=['-timestamp'], name='client_clie_timesta_a9e61f_idx'),
        ),
        migrations.AddIndex(
            model_name='clientactivitylog',
            index=models.Index(fields=['client', '-timestamp'], name='client_clie_client__7b9622_idx'),
        ),
    ]
