# Generated by Django 4.2.23 on 2025-07-15 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_app", "0002_clientprofile_alter_citypostalcode_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientsupplier",
            name="tenant_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subclients",
                to="client_app.clientsupplier",
                verbose_name="Tenant (Holding/Operativa)",
            ),
        ),
    ]
