# Generated by Django 4.2.23 on 2025-07-21 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_clientsupplier_tenant_id"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="citypostalcode",
            new_name="client_city_postal__bddf1a_idx",
            old_name="client_app__postal__8c341e_idx",
        ),
        migrations.RenameIndex(
            model_name="citypostalcode",
            new_name="client_city_city_77cf8f_idx",
            old_name="client_app__city_79d885_idx",
        ),
        migrations.RenameIndex(
            model_name="clientactivitylog",
            new_name="client_clie_timesta_a9e61f_idx",
            old_name="client_app__timesta_b6ca4c_idx",
        ),
        migrations.RenameIndex(
            model_name="clientactivitylog",
            new_name="client_clie_client__7b9622_idx",
            old_name="client_app__client__277058_idx",
        ),
        migrations.RenameIndex(
            model_name="clientsupplier",
            new_name="client_clie_name_fe02e2_idx",
            old_name="client_app__name_d320c3_idx",
        ),
        migrations.RenameIndex(
            model_name="clientsupplier",
            new_name="client_clie_oib_5d8873_idx",
            old_name="client_app__oib_0c918a_idx",
        ),
        migrations.RenameIndex(
            model_name="clientsupplier",
            new_name="client_clie_relatio_704cd5_idx",
            old_name="client_app__relatio_181d73_idx",
        ),
        migrations.AlterField(
            model_name="clientactivitylog",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="client.clientsupplier",
                verbose_name="Klijent/Dobavljač",
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientprofile",
                to="client.clientsupplier",
            ),
        ),
        migrations.AlterField(
            model_name="clientsupplier",
            name="tenant_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subclients",
                to="client.clientsupplier",
                verbose_name="Tenant (Holding/Operativa)",
            ),
        ),
    ]
