# Generated by Django 4.2.23 on 2025-07-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_client_app__postal__8c341e_idx_client_city_postal__bddf1a_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='citypostalcode',
            new_name='client_city_postal__bddf1a_idx',
            old_name='client__postal__8c341e_idx',
        ),
        migrations.RenameIndex(
            model_name='citypostalcode',
            new_name='client_city_city_77cf8f_idx',
            old_name='client__city_79d885_idx',
        ),
        migrations.RenameIndex(
            model_name='clientactivitylog',
            new_name='client_clie_timesta_a9e61f_idx',
            old_name='client__timesta_b6ca4c_idx',
        ),
        migrations.RenameIndex(
            model_name='clientactivitylog',
            new_name='client_clie_client__7b9622_idx',
            old_name='client__client__277058_idx',
        ),
        migrations.RenameIndex(
            model_name='clientsupplier',
            new_name='client_clie_name_fe02e2_idx',
            old_name='client__name_d320c3_idx',
        ),
        migrations.RenameIndex(
            model_name='clientsupplier',
            new_name='client_clie_oib_5d8873_idx',
            old_name='client__oib_0c918a_idx',
        ),
        migrations.RenameIndex(
            model_name='clientsupplier',
            new_name='client_clie_relatio_704cd5_idx',
            old_name='client__relatio_181d73_idx',
        ),
    ]
