# Generated by Django 4.2.23 on 2025-08-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "client_app",
            "0004_rename_client_app__postal__8c341e_idx_client_city_postal__bddf1a_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="citypostalcode",
            new_name="client_app__postal__8c341e_idx",
            old_name="client_city_postal__bddf1a_idx",
        ),
        migrations.RenameIndex(
            model_name="citypostalcode",
            new_name="client_app__city_79d885_idx",
            old_name="client_city_city_77cf8f_idx",
        ),
        migrations.RenameIndex(
            model_name="clientactivitylog",
            new_name="client_app__timesta_b6ca4c_idx",
            old_name="client_clie_timesta_a9e61f_idx",
        ),
        migrations.RenameIndex(
            model_name="clientactivitylog",
            new_name="client_app__client__277058_idx",
            old_name="client_clie_client__7b9622_idx",
        ),
        migrations.RenameIndex(
            model_name="clientsupplier",
            new_name="client_app__name_d320c3_idx",
            old_name="client_clie_name_fe02e2_idx",
        ),
        migrations.RenameIndex(
            model_name="clientsupplier",
            new_name="client_app__oib_0c918a_idx",
            old_name="client_clie_oib_5d8873_idx",
        ),
        migrations.RenameIndex(
            model_name="clientsupplier",
            new_name="client_app__relatio_181d73_idx",
            old_name="client_clie_relatio_704cd5_idx",
        ),
    ]
