# Generated by Django 4.2.23 on 2025-08-27 07:07

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "client_app",
            "0005_rename_client_city_postal__bddf1a_idx_client_app__postal__8c341e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsupplier",
            name="oib",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[common.validators.validate_oib],
                verbose_name="OIB",
            ),
        ),
    ]
