[tool.black]
line-length = 100
target-version = ["py311"]
# Exclude migrations and legacy_disabled on all platforms (supports "/" and "\\")
extend-exclude = '''
(
  (?:^|[\\/])legacy_disabled(?:[\\/].*)?$|
  (?:^|[\\/]).*?[\\/]migrations(?:[\\/].*)?$
)
'''
# (opcionalno) zadrži ako želiš
# skip-string-normalization = true

[tool.ruff]
line-length = 100
target-version = "py311"
lint.select = ["E","F","I","B","UP"]
exclude = ["**/migrations/**", "**/legacy_disabled/**"]

[tool.ruff.lint.per-file-ignores]
"tests/**.py" = ["E501", "E402", "B007"]
"erp_system/settings/*.py" = ["F401", "F403", "F405"]
"config/settings/*.py" = ["F401", "F403", "F405"]

[tool.ruff.format]
quote-style = "double"
