# Generated by Django 4.2.23 on 2025-07-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proizvodnja', '0006_alter_tipprojekta_tenant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipprojekta',
            name='tenant_id',
        ),
    ]
