# Generated by Django 4.2.14 on 2025-08-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proizvodnja', '0007_remove_tipprojekta_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radninalog',
            name='grupa_posla',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='radni_nalozi',
                to='proizvodnja.grupaposlova',
                verbose_name='Grupa Poslova',
            ),
        ),
        migrations.AlterField(
            model_name='radninalog',
            name='projekt',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='radni_nalozi',
                to='proizvodnja.projekt',
                verbose_name='Projekt',
            ),
        ),
    ]
