# Generated by Django 4.2.23 on 2025-08-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
