# Generated by Django 4.2.23 on 2025-08-18 13:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_merge_0003_alter_tenant_domain_0003_tenantsettings'),
        ('financije', '0002_initial'),
        ('ljudski_resursi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('division', models.CharField(max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitShareRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=64)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pool_50', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pool_30', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pool_20', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ramp_up_min_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'invoice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profit_share_runs',
                        to='financije.invoice',
                    ),
                ),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitShareParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_from_30', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ramp_up_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    'employee',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ljudski_resursi.employee'),
                ),
                (
                    'run',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='participants',
                        to='project_costing.profitsharerun',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ProfitShareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_share', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('worker_share', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5)),
                ('dynamic_floor_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=4)),
                (
                    'floor_cap_per_month',
                    models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=8),
                ),
                ('ramp_up_company_pct', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=4)),
                ('ramp_up_worker_pct', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=4)),
                ('ramp_up_fund_pct', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=4)),
                (
                    'project',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profit_share_config',
                        to='project_costing.project',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ProfitShareAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                (
                    'employee',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ljudski_resursi.employee'),
                ),
                (
                    'run',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='adjustments',
                        to='project_costing.profitsharerun',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='profitsharerun',
            constraint=models.UniqueConstraint(fields=('tenant', 'ref'), name='uniq_profitshare_ref_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='profitsharerun',
            constraint=models.UniqueConstraint(fields=('invoice',), name='uniq_profitshare_invoice'),
        ),
    ]
