# Generated by Django 4.2.23 on 2025-08-19 11:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_costing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitsharerun',
            name='posted_entry_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profitsharerun',
            name='rounding_diff',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
