# Generated by Django 4.2.18 on 2025-01-30 20:18

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ljudski_resursi", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nabava", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artikl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="Naziv artikla"),
                ),
                ("opis", models.TextField(blank=True, null=True, verbose_name="Opis")),
                (
                    "sifra",
                    models.CharField(max_length=50, unique=True, verbose_name="Šifra artikla"),
                ),
                ("jm", models.CharField(max_length=20, verbose_name="Jedinica mjere")),
                (
                    "min_kolicina",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Minimalna količina",
                    ),
                ),
                (
                    "trenutna_kolicina",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Trenutna količina",
                    ),
                ),
                (
                    "nabavna_cijena",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Nabavna cijena",
                    ),
                ),
                (
                    "prodajna_cijena",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Prodajna cijena",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivno"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dobavljac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artikli",
                        to="nabava.dobavljac",
                        verbose_name="Dobavljač",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artikl",
                "verbose_name_plural": "Artikli",
                "ordering": ["naziv"],
            },
        ),
        migrations.CreateModel(
            name="Izdatnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broj_izdatnice",
                    models.CharField(max_length=20, unique=True, verbose_name="Broj izdatnice"),
                ),
                ("datum", models.DateField(verbose_name="Datum izdavanja")),
                (
                    "napomena",
                    models.TextField(blank=True, null=True, verbose_name="Napomena"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_izdatnice",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kreirao",
                    ),
                ),
                (
                    "preuzeo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preuzete_izdatnice",
                        to="ljudski_resursi.employee",
                        verbose_name="Preuzeo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Izdatnica",
                "verbose_name_plural": "Izdatnice",
                "ordering": ["-datum", "-broj_izdatnice"],
            },
        ),
        migrations.CreateModel(
            name="Primka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broj_primke",
                    models.CharField(max_length=20, unique=True, verbose_name="Broj primke"),
                ),
                ("datum", models.DateField(verbose_name="Datum primke")),
                (
                    "napomena",
                    models.TextField(blank=True, null=True, verbose_name="Napomena"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_primke",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kreirao",
                    ),
                ),
                (
                    "dobavljac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nabava.dobavljac",
                        verbose_name="Dobavljač",
                    ),
                ),
            ],
            options={
                "verbose_name": "Primka",
                "verbose_name_plural": "Primke",
                "ordering": ["-datum", "-broj_primke"],
            },
        ),
        migrations.CreateModel(
            name="SkladisteResurs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="Naziv resursa"),
                ),
                ("opis", models.TextField(blank=True, null=True, verbose_name="Opis")),
                (
                    "kolicina",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Količina"),
                ),
                ("lokacija", models.CharField(max_length=255, verbose_name="Lokacija")),
            ],
            options={
                "verbose_name": "Skladišni resurs",
                "verbose_name_plural": "Skladišni resursi",
                "ordering": ["naziv"],
            },
        ),
        migrations.CreateModel(
            name="Zona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naziv", models.CharField(max_length=100, verbose_name="Naziv zone")),
                (
                    "opis",
                    models.TextField(blank=True, null=True, verbose_name="Opis zone"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrimkaStavka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kolicina",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Količina",
                    ),
                ),
                (
                    "cijena",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Cijena",
                    ),
                ),
                (
                    "artikl",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="skladiste.artikl",
                        verbose_name="Artikl",
                    ),
                ),
                (
                    "primka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stavke",
                        to="skladiste.primka",
                        verbose_name="Primka",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stavka primke",
                "verbose_name_plural": "Stavke primke",
            },
        ),
        migrations.CreateModel(
            name="Materijal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("na_skladistu", "Na skladištu"),
                            ("naruceno_dostava", "Naručeno - Čeka dostavu"),
                            ("naruceno_placanje", "Naručeno - Čeka plaćanje"),
                            ("nije_naruceno", "Nije naručeno"),
                        ],
                        default="nije_naruceno",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="Naziv materijala"),
                ),
                (
                    "cijena",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Cijena"),
                ),
                (
                    "kolicina",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Količina"),
                ),
                ("opis", models.TextField(blank=True, null=True, verbose_name="Opis")),
                (
                    "datum_dostave",
                    models.DateField(blank=True, null=True, verbose_name="Datum dostave"),
                ),
                ("current_stock", models.PositiveIntegerField(default=0)),
                ("min_required_stock", models.PositiveIntegerField(default=0)),
                (
                    "artikl",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materijal",
                        to="skladiste.artikl",
                    ),
                ),
                (
                    "narudzbenica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nabava.narudzbenica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Materijal",
                "verbose_name_plural": "Materijali",
                "ordering": ["naziv"],
            },
        ),
        migrations.CreateModel(
            name="Lokacija",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=100, verbose_name="Naziv lokacije"),
                ),
                ("opis", models.TextField(blank=True, null=True, verbose_name="Opis")),
                (
                    "zona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="skladiste.zona",
                        verbose_name="Zona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kategorija",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=100, unique=True, verbose_name="Naziv kategorije"),
                ),
                ("opis", models.TextField(blank=True, null=True, verbose_name="Opis")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivno"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="skladiste.kategorija",
                        verbose_name="Nadređena kategorija",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategorija",
                "verbose_name_plural": "Kategorije",
                "ordering": ["naziv"],
            },
        ),
        migrations.CreateModel(
            name="IzdatnicaStavka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kolicina",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Količina",
                    ),
                ),
                (
                    "artikl",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="skladiste.artikl",
                        verbose_name="Artikl",
                    ),
                ),
                (
                    "izdatnica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stavke",
                        to="skladiste.izdatnica",
                        verbose_name="Izdatnica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stavka izdatnice",
                "verbose_name_plural": "Stavke izdatnice",
            },
        ),
        migrations.CreateModel(
            name="HTZOprema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vrsta",
                    models.CharField(max_length=100, verbose_name="Vrsta HTZ opreme"),
                ),
                ("stanje", models.CharField(max_length=50, verbose_name="Stanje")),
                (
                    "is_assigned",
                    models.BooleanField(default=False, verbose_name="Trenutačno zaduženo?"),
                ),
                (
                    "htz_equipment_tracking",
                    models.BooleanField(default=False, verbose_name="Praćenje zaduženja HTZ opreme"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ljudski_resursi.employee",
                        verbose_name="Dodijeljeno djelatniku",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DnevnikDogadaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datum",
                    models.DateTimeField(auto_now_add=True, verbose_name="Datum"),
                ),
                ("dogadaj", models.CharField(max_length=255, verbose_name="Događaj")),
                (
                    "artikl",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dnevnik_dogadaja",
                        to="skladiste.artikl",
                        verbose_name="Artikl (ako se odnosi)",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="artikl",
            name="kategorija",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artikli",
                to="skladiste.kategorija",
                verbose_name="Kategorija",
            ),
        ),
        migrations.AddField(
            model_name="artikl",
            name="lokacija",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artikli",
                to="skladiste.lokacija",
                verbose_name="Lokacija",
            ),
        ),
        migrations.CreateModel(
            name="Alat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naziv", models.CharField(max_length=100, verbose_name="Naziv alata")),
                (
                    "inventarski_broj",
                    models.CharField(max_length=50, verbose_name="Inventarski broj"),
                ),
                (
                    "zaduzen",
                    models.BooleanField(default=False, verbose_name="Zadužen?"),
                ),
                (
                    "is_assigned",
                    models.BooleanField(default=False, verbose_name="Je li dodijeljen?"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ljudski_resursi.employee",
                        verbose_name="Zaduženi djelatnik",
                    ),
                ),
            ],
        ),
    ]
