# Generated by Django 4.2.23 on 2025-07-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skladiste', '0003_alter_alat_id_alter_artikl_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona',
            name='tenant_id',
        ),
    ]
