# Generated by Django 4.2.23 on 2025-08-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skladiste", "0003_alter_alat_id_alter_artikl_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artikl",
            options={},
        ),
        migrations.AlterModelOptions(
            name="materijal",
            options={},
        ),
        migrations.AlterModelOptions(
            name="primka",
            options={},
        ),
        migrations.AlterModelOptions(
            name="zona",
            options={},
        ),
        migrations.AlterField(
            model_name="artikl",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="materijal",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="primka",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="zona",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
