# Generated by Django 4.2.23 on 2025-07-21 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audittrail",
            options={
                "verbose_name": "Audit Trail",
                "verbose_name_plural": "Audit Trails",
            },
        ),
        migrations.RenameField(
            model_name="audittrail",
            old_name="audit_notes",
            new_name="notes",
        ),
        migrations.RemoveField(
            model_name="audittrail",
            name="action",
        ),
        migrations.RemoveField(
            model_name="audittrail",
            name="action_taken",
        ),
        migrations.RemoveField(
            model_name="audittrail",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="audittrail",
            name="timestamp",
        ),
        # Skipping change_type and content_object reintroduction in stub path.
        migrations.AlterField(
            model_name="audittrail",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
