# Generated by Django 4.2.23 on 2025-07-27 11:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ljudski_resursi', '0009_remove_hierarchicallevel_tenant_id'),
        ('common', '0003_alter_audittrail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audittrail',
            options={},
        ),
        migrations.RenameField(
            model_name='audittrail',
            old_name='notes',
            new_name='audit_notes',
        ),
        migrations.RemoveField(
            model_name='audittrail',
            name='change_type',
        ),
        migrations.RemoveField(
            model_name='audittrail',
            name='content_object',
        ),
        migrations.AddField(
            model_name='audittrail',
            name='action',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audittrail',
            name='action_taken',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audittrail',
            name='recipient',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='audittrail_recipient',
                to='ljudski_resursi.employee',
            ),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='audittrail_user',
                to='ljudski_resursi.employee',
            ),
        ),
    ]
