# Generated by Django 4.2.23 on 2025-08-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_apiidempotency"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apiidempotency",
            new_name="common_apii_tenant__998aab_idx",
            old_name="api_idem_tpmk_idx",
        ),
        migrations.AlterField(
            model_name="apiidempotency",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="audittrail",
            name="action",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="audittrail",
            name="action_taken",
            field=models.CharField(max_length=200),
        ),
    ]
