# Generated by Django 4.2.23 on 2025-08-27 07:07

import common.models.blob
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_merge_20250826_0001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blob",
            name="retained_until",
            field=models.DateTimeField(default=common.models.blob.default_retained_until),
        ),
    ]
