# Generated by Django 4.2.23 on 2025-07-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="domain",
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name="Domain"),
            preserve_default=False,
        ),
    ]
