# Generated by Django 4.2.14 on 2025-08-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Domain'),
        ),
    ]
