# Generated by Django 3.2.25 on 2025-08-18 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramp_up_min_net', models.DecimalField(decimal_places=2, default=800.0, max_digits=10)),
                ('acc_expense_ops', models.CharField(default='4000', max_length=20)),
                ('acc_expense_payroll', models.CharField(default='4100', max_length=20)),
                ('acc_equity_profit', models.CharField(default='5000', max_length=20)),
                ('acc_ar_customers', models.CharField(default='1200', max_length=20)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
        ),
    ]
