# Generated by Django 4.2.18 on 2025-01-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FieldVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visited_client",
                    models.CharField(max_length=255, verbose_name="Posjećeni klijent"),
                ),
                ("date_of_visit", models.DateField(verbose_name="Datum posjete")),
                (
                    "purpose",
                    models.TextField(
                        blank=True, null=True, verbose_name="Svrha posjete / bilješke"
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Visit",
                "verbose_name_plural": "Field Visits",
                "ordering": ["-date_of_visit"],
            },
        ),
        migrations.CreateModel(
            name="ProjectServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Naziv usluge/projekta",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
            ],
            options={
                "verbose_name": "Project/Service Type",
                "verbose_name_plural": "Project/Service Types",
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Broj ponude"
                    ),
                ),
                ("valid_until", models.DateField(verbose_name="Vrijedi do")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nacrt"),
                            ("sent", "Poslano klijentu"),
                            ("approved", "Odobreno"),
                            ("rejected", "Odbijeno"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status ponude",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Ukupan iznos (€)"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Popust (%)",
                    ),
                ),
                (
                    "revision_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Broj revizija"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(max_length=255, verbose_name="Kreirao/la"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.CharField(max_length=255, verbose_name="Klijent")),
                (
                    "contract_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Broj ugovora"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nacrt"),
                            ("active", "Aktivan"),
                            ("closed", "Zatvoren"),
                            ("cancelled", "Otkazan"),
                        ],
                        default="draft",
                        max_length=50,
                        verbose_name="Status ugovora",
                    ),
                ),
                (
                    "public_tender_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Broj javnog natječaja",
                    ),
                ),
                (
                    "bank_guarantee_required",
                    models.BooleanField(
                        default=False, verbose_name="Bankarska garancija tražena?"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Ukupan iznos (€)"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Popust (%)",
                    ),
                ),
                (
                    "delivery_schedule",
                    models.TextField(
                        blank=True, null=True, verbose_name="Raspored isporuke"
                    ),
                ),
                (
                    "client_specific_reqs",
                    models.TextField(
                        blank=True, null=True, verbose_name="Posebni zahtjevi klijenta"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(max_length=255, verbose_name="Kreirao/la"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Naziv leada / prilike"
                    ),
                ),
                (
                    "lead_source",
                    models.CharField(
                        choices=[
                            ("field_visit", "Terenska posjeta"),
                            ("tender", "Javna nabava / natječaj"),
                            ("referral", "Preporuka postojećeg klijenta"),
                            ("marketing", "Digitalni marketing / kampanja"),
                            ("trade_fair", "Sajam / industrijski događaj"),
                            ("other", "Ostalo"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Izvor leada",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "Novi lead"),
                            ("qualified", "Kvalificiran"),
                            ("negotiation", "Pregovori"),
                            ("won", "Zatvoren - dobiveno"),
                            ("lost", "Zatvoren - izgubljeno"),
                        ],
                        default="new",
                        max_length=50,
                        verbose_name="Faza prodajnog ciklusa",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Budžet (procjena)",
                    ),
                ),
                (
                    "authority",
                    models.BooleanField(
                        default=False, verbose_name="Klijent ima ovlasti za potpis?"
                    ),
                ),
                (
                    "need",
                    models.BooleanField(
                        default=False, verbose_name="Jasna potreba klijenta?"
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Vremenski okvir (BANT)",
                    ),
                ),
                (
                    "public_tender_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Broj javnog natječaja",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Vrijeme kreiranja"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zadnje ažuriranje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Opportunity (Lead)",
                "verbose_name_plural": "Sales Opportunities (Leads)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.CharField(max_length=255, verbose_name="Klijent")),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Broj narudžbe"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Na čekanju"),
                            ("completed", "Završeno"),
                            ("cancelled", "Otkazano"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status narudžbe",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Ukupan iznos (€)"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Popust (%)",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(max_length=255, verbose_name="Kreirao/la"),
                ),
                (
                    "date_approved_by_client",
                    models.DateField(
                        blank=True, null=True, verbose_name="Klijent potvrdio (datum)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkOrderInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proizvod",
                    models.CharField(
                        max_length=255, verbose_name="Proizvod/Komponenta"
                    ),
                ),
                ("kolicina", models.PositiveIntegerField(verbose_name="Količina")),
                (
                    "cijena",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cijena (€)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Order Input",
                "verbose_name_plural": "Work Order Inputs",
            },
        ),
    ]
