# Generated by Django 4.2.23 on 2025-08-18 13:57

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('service_lines', models.JSONField(default=list, verbose_name='Stavke usluge')),
                ('material_lines', models.JSONField(default=list, verbose_name='Stavke materijala')),
                (
                    'total_amount',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Ukupan iznos'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('draft', 'Nacrt'), ('approved', 'Odobreno')], default='draft', max_length=20
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Klijent')),
                ('quote_number', models.CharField(max_length=50, unique=True, verbose_name='Broj ponude')),
                ('valid_until', models.DateField(verbose_name='Vrijedi do')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Nacrt'),
                            ('sent', 'Poslano'),
                            ('approved', 'Odobreno'),
                            ('rejected', 'Odbijeno'),
                        ],
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ukupan iznos (€)')),
                (
                    'discount',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Popust (%)'
                    ),
                ),
                ('revision_count', models.PositiveIntegerField(default=0, verbose_name='Broj revizija')),
                ('created_by', models.CharField(max_length=255, verbose_name='Kreirao/la')),
                (
                    'linked_production_order_ref',
                    models.CharField(blank=True, max_length=64, null=True, verbose_name='Ref proizvodnje'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Naziv prilike')),
                (
                    'client_name',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Klijent (naziv)'),
                ),
                (
                    'lead_source',
                    models.CharField(
                        choices=[
                            ('field_visit', 'Terenska posjeta'),
                            ('tender', 'Javna nabava / natječaj'),
                            ('referral', 'Preporuka postojećeg klijenta'),
                            ('marketing', 'Digitalni marketing / kampanja'),
                            ('trade_fair', 'Sajam / industrijski događaj'),
                            ('other', 'Ostalo'),
                        ],
                        default='other',
                        max_length=50,
                    ),
                ),
                (
                    'stage',
                    models.CharField(
                        choices=[
                            ('new', 'Novi lead'),
                            ('qualified', 'Kvalificiran'),
                            ('negotiation', 'Pregovori'),
                            ('won', 'Zatvoren - dobiveno'),
                            ('lost', 'Zatvoren - izgubljeno'),
                        ],
                        default='new',
                        max_length=50,
                    ),
                ),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Vrijednost')),
                (
                    'budget_estimate',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Budžet (procjena)'
                    ),
                ),
                (
                    'public_tender_number',
                    models.CharField(blank=True, max_length=100, null=True, verbose_name='Broj javnog natječaja'),
                ),
                (
                    'project_service_type',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Vrsta usluge/projekta'),
                ),
                ('notes', models.TextField(blank=True, verbose_name='Bilješke')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sales Opportunity',
                'verbose_name_plural': 'Sales Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Klijent')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Broj narudžbe')),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', 'Na čekanju'), ('completed', 'Završeno'), ('cancelled', 'Otkazano')],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ukupan iznos (€)')),
                (
                    'discount',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Popust (%)'
                    ),
                ),
                ('created_by', models.CharField(max_length=255, verbose_name='Kreirao/la')),
                (
                    'date_approved_by_client',
                    models.DateField(blank=True, null=True, verbose_name='Klijent potvrdio (datum)'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'quotation',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='orders',
                        to='prodaja.quotation',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Klijent')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Broj ugovora')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Nacrt'),
                            ('active', 'Aktivan'),
                            ('closed', 'Zatvoren'),
                            ('cancelled', 'Otkazan'),
                        ],
                        default='draft',
                        max_length=50,
                    ),
                ),
                (
                    'public_tender_number',
                    models.CharField(blank=True, max_length=100, null=True, verbose_name='Broj javnog natječaja'),
                ),
                (
                    'bank_guarantee_required',
                    models.BooleanField(default=False, verbose_name='Bankarska garancija tražena?'),
                ),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ukupan iznos (€)')),
                (
                    'discount',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Popust (%)'
                    ),
                ),
                ('delivery_schedule', models.TextField(blank=True, null=True, verbose_name='Raspored isporuke')),
                (
                    'client_specific_reqs',
                    models.TextField(blank=True, null=True, verbose_name='Posebni zahtjevi klijenta'),
                ),
                (
                    'related_production_order_ref',
                    models.CharField(blank=True, max_length=64, null=True, verbose_name='Ref radnog naloga'),
                ),
                ('created_by', models.CharField(max_length=255, verbose_name='Kreirao/la')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'sales_order',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sales_contract',
                        to='prodaja.salesorder',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='opportunity',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='quotations',
                to='prodaja.salesopportunity',
            ),
        ),
        migrations.CreateModel(
            name='FieldVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Planirani datum')),
                (
                    'status',
                    models.CharField(
                        choices=[('planned', 'Planirano'), ('completed', 'Završeno'), ('cancelled', 'Otkazano')],
                        default='planned',
                        max_length=20,
                        verbose_name='Status',
                    ),
                ),
                ('notes', models.TextField(blank=True, verbose_name='Bilješke')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'opportunity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='field_visits',
                        to='prodaja.salesopportunity',
                        verbose_name='Prodajna prilika',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Field Visit',
                'verbose_name_plural': 'Field Visits',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
