# Generated by Django 4.2.18 on 2025-01-30 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # Removed dependencies on legacy 'client' and 'proizvodnja' apps for MVP
    dependencies = [
        ("prodaja", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    # Skip legacy RadniNalog FK (production app disabled)
        migrations.AddField(
            model_name="salesorder",
            name="quotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="prodaja.quotation",
                verbose_name="Iz ponude (Quotation)",
            ),
        ),
        migrations.AddField(
            model_name="salesopportunity",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Odgovorni prodajni predstavnik",
            ),
        ),
    # Skip legacy CRM client FK
        migrations.AddField(
            model_name="salesopportunity",
            name="project_service_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prodaja.projectservicetype",
                verbose_name="Vrsta usluge/projekta",
            ),
        ),
    # Skip related production order FK
        migrations.AddField(
            model_name="salescontract",
            name="sales_order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_contract",
                to="prodaja.salesorder",
                verbose_name="Povezana narudžba",
            ),
        ),
    # Skip quotation client FK
    # Skip linked production order FK
        migrations.AddField(
            model_name="quotation",
            name="opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations",
                to="prodaja.salesopportunity",
                verbose_name="Pripadajuća prilika (Opportunity)",
            ),
        ),
        migrations.AddField(
            model_name="fieldvisit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Prodajni predstavnik",
            ),
        ),
        migrations.AddField(
            model_name="fieldvisit",
            name="opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="field_visits",
                to="prodaja.salesopportunity",
                verbose_name="Povezana prilika",
            ),
        ),
    ]
