# Generated by Django 4.2.18 on 2025-01-30 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("prodaja", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proizvodnja", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderinput",
            name="radni_nalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_order_inputs",
                to="proizvodnja.radninalog",
                verbose_name="Radni nalog",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="quotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="prodaja.quotation",
                verbose_name="Iz ponude (Quotation)",
            ),
        ),
        migrations.AddField(
            model_name="salesopportunity",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Odgovorni prodajni predstavnik",
            ),
        ),
        migrations.AddField(
            model_name="salesopportunity",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="client.clientsupplier",
                verbose_name="Klijent (CRM)",
            ),
        ),
        migrations.AddField(
            model_name="salesopportunity",
            name="project_service_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prodaja.projectservicetype",
                verbose_name="Vrsta usluge/projekta",
            ),
        ),
        migrations.AddField(
            model_name="salescontract",
            name="related_production_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="proizvodnja.radninalog",
                verbose_name="Povezani Radni Nalog (ako postoji)",
            ),
        ),
        migrations.AddField(
            model_name="salescontract",
            name="sales_order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_contract",
                to="prodaja.salesorder",
                verbose_name="Povezana narudžba",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="client.clientsupplier",
                verbose_name="Klijent (CRM)",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="linked_production_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="proizvodnja.radninalog",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations",
                to="prodaja.salesopportunity",
                verbose_name="Pripadajuća prilika (Opportunity)",
            ),
        ),
        migrations.AddField(
            model_name="fieldvisit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Prodajni predstavnik",
            ),
        ),
        migrations.AddField(
            model_name="fieldvisit",
            name="opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="field_visits",
                to="prodaja.salesopportunity",
                verbose_name="Povezana prilika",
            ),
        ),
    ]
