# Generated by Django 4.2.18 on 2025-02-01 02:39

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prodaja", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="tender_documents/", verbose_name="Dokument"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Opis dokumenta"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Datum uploada"),
                ),
            ],
            options={
                "verbose_name": "Dokument natječaja",
                "verbose_name_plural": "Dokumenti natječaja",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TenderPreparation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tender_instructions",
                    models.TextField(blank=True, null=True, verbose_name="Upute za ponuditelje"),
                ),
                (
                    "evaluation_criteria",
                    models.JSONField(blank=True, null=True, verbose_name="Kriteriji evaluacije"),
                ),
                (
                    "tender_validity",
                    models.DateField(blank=True, null=True, verbose_name="Rok valjanosti ponude"),
                ),
                (
                    "delivery_opening_datetime",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Datum i vrijeme otvaranja ponuda",
                    ),
                ),
                (
                    "payment_terms",
                    models.TextField(blank=True, null=True, verbose_name="Uvjeti plaćanja"),
                ),
                (
                    "warranty_terms",
                    models.TextField(blank=True, null=True, verbose_name="Uvjeti jamstva"),
                ),
                (
                    "seriousness_guarantee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3.00"),
                        help_text="Obično 3%",
                        max_digits=5,
                        verbose_name="Postotak garancije za ozbiljnost ponude",
                    ),
                ),
                (
                    "seriousness_guarantee_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Iznos garancije za ozbiljnost ponude",
                    ),
                ),
                (
                    "performance_guarantee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Obično 10%",
                        max_digits=5,
                        verbose_name="Postotak garancije za uredno izvršenje ugovora",
                    ),
                ),
                (
                    "performance_guarantee_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Iznos garancije za uredno izvršenje ugovora",
                    ),
                ),
                (
                    "warranty_guarantee_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Unesite vrijednost u rasponu, npr. 2 do 10%",
                        max_digits=5,
                        null=True,
                        verbose_name="Postotak bankarske garancije za jamstveni rok",
                    ),
                ),
                (
                    "warranty_guarantee_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Iznos bankarske garancije za jamstveni rok",
                    ),
                ),
                (
                    "cashflow_plan",
                    models.JSONField(blank=True, null=True, verbose_name="Plan cashflow-a"),
                ),
                (
                    "nabava_updates",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Ažurirane ponude materijala iz nabave",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Dodatne napomene"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nacrt"),
                            ("in_preparation", "U pripremi"),
                            ("ready", "Spremno za ponudu"),
                            ("submitted", "Podneseno"),
                        ],
                        default="draft",
                        max_length=50,
                        verbose_name="Status pripreme tendera",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vrijeme kreiranja"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Zadnje ažuriranje"),
                ),
                (
                    "opportunity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tender_preparation",
                        to="prodaja.salesopportunity",
                        verbose_name="Prilika (natječaj)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Priprema tendera",
                "verbose_name_plural": "Pripreme tendera",
                "ordering": ["-created_at"],
            },
        ),
    ]
