# Generated by Django 4.2.18 on 2025-02-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Dropped legacy dependency on projektiranje_app (app removed)
        ("prodaja", "0003_tenderdocument_tenderpreparation"),
    ]

    operations = [
        # Removed proposal_drawings M2M to projektiranje_app.CADDocument (stubbed out).
        migrations.AddField(
            model_name="tenderpreparation",
            name="tender_documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="tender_preparations",
                to="prodaja.tenderdocument",
                verbose_name="Dokumentacija natječaja",
            ),
        ),
    ]
