# Generated by Django 4.2.18 on 2025-02-02 00:45

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proizvodnja", "0004_alter_radninalog_gantogram_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projektiranje", "0003_delete_dokumentacijaprojektiranja_and_more"),
        ("financije", "0006_financialanalysis"),
        ("prodaja", "0004_tenderpreparation_proposal_drawings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenderpreparation",
            name="tender_documents",
        ),
        migrations.AddField(
            model_name="tenderdocument",
            name="tender_preparation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="prodaja.tenderpreparation",
                verbose_name="Tender priprema",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenderpreparation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="tenderpreparation",
            name="estimated_production_time",
            field=models.DurationField(blank=True, null=True, verbose_name="Procijenjeno vrijeme proizvodnje"),
        ),
        migrations.AddField(
            model_name="tenderpreparation",
            name="financial_analysis",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tender",
                to="financije.financialanalysis",
                verbose_name="Financijska analiza",
            ),
        ),
        migrations.AddField(
            model_name="tenderpreparation",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                max_digits=8,
                verbose_name="Satnica (€)",
            ),
        ),
        migrations.AddField(
            model_name="tenderpreparation",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="tenderpreparation",
            name="labor_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Radni sati",
            ),
        ),
        migrations.AddField(
            model_name="tenderpreparation",
            name="material_costs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Troškovi materijala",
            ),
        ),
        migrations.AddField(
            model_name="tenderpreparation",
            name="payment_schedule",
            field=models.JSONField(blank=True, default=dict, verbose_name="Plan plaćanja"),
        ),
        migrations.AddField(
            model_name="tenderpreparation",
            name="production_capacity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="proizvodnja.projekt",
                verbose_name="Povezani projekt",
            ),
        ),
        migrations.AddField(
            model_name="tenderpreparation",
            name="project_manager",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Voditelj projekta (ime)",
            ),
        ),
        migrations.AddField(
            model_name="tenderpreparation",
            name="required_documents",
            field=models.JSONField(blank=True, default=dict, verbose_name="Obavezna dokumentacija"),
        ),
        migrations.AddField(
            model_name="tenderpreparation",
            name="technical_drawings",
            field=models.ManyToManyField(
                blank=True,
                related_name="tenders",
                to="projektiranje.designtask",
                verbose_name="Tehnički nacrti",
            ),
        ),
        migrations.AddField(
            model_name="tenderpreparation",
            name="technical_specs",
            field=models.JSONField(blank=True, default=dict, verbose_name="Tehničke specifikacije"),
        ),
        migrations.AddField(
            model_name="tenderpreparation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
    ]
