# Generated by Django 4.2.18 on 2025-02-10 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prodaja', '0006_alter_tenderpreparation_options_tendersummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderlabor',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ukupni trošak'),
        ),
        migrations.AddField(
            model_name='tendermaterial',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ukupna cijena'),
        ),
        migrations.CreateModel(
            name='TenderRasclamba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('naziv_stavke', models.CharField(max_length=255, verbose_name='Naziv stavke')),
                ('sati_rada', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Sati rada')),
                ('nas_materijal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Naš materijal')),
                ('vanjska_usluga', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Vanjska usluga')),
                ('oprema_dijelovi', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Oprema/dijelovi')),
                ('dobavljac', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dobavljač')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasclamba_items', to='prodaja.tenderpreparation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenderPosredniTroskovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.CharField(max_length=255, verbose_name='Opis troška')),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Mjesečni trošak')),
                ('project_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Trošak po projektu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_posredni_troskovi', to='prodaja.tenderpreparation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenderNeposredniTroskovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.CharField(max_length=255, verbose_name='Opis troška')),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Mjesečni trošak')),
                ('project_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Trošak po projektu')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Koeficijent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_neposredni_troskovi', to='prodaja.tenderpreparation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
