# Generated by Django 4.2.18 on 2025-02-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prodaja", "0007_tenderlabor_total_cost_tendermaterial_total_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesopportunity",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Vrijednost"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salesopportunity",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Bilješke"),
        ),
    ]
