# Generated by Django 4.2.23 on 2025-07-21 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # Removed dependencies on legacy 'projektiranje' and 'client' apps for MVP
    dependencies = [
        ("prodaja", "0010_projectservicetype_tenant_id_and_more"),
    ]

    # All operations in this migration relate to legacy models or id type adjustments no longer necessary in MVP.
    operations = []
