# Generated by Django 4.2.23 on 2025-07-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0011_alter_fieldvisit_id_alter_projectservicetype_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectservicetype',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='tenderneposrednitroskovi',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='tenderposrednitroskovi',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='tenderpreparation',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='tenderrasclamba',
            name='tenant_id',
        ),
    ]
