# Generated by Django 4.2.23 on 2025-08-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prodaja", "0003_invoice_number_constraint"),
        ("prodaja", "0011_alter_fieldvisit_id_alter_projectservicetype_id_and_more"),
    ]

    operations = []
