# Generated by Django 4.2.23 on 2025-08-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client_app", "0002_clientprofile_alter_citypostalcode_options_and_more"),
        ("financije", "0014_alter_breakevensnapshot_unique_together_and_more"),
        ("prodaja", "0012_merge_20250821_1204"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectservicetype",
            name="tenant_id",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="linked_production_order",
        ),
        migrations.RemoveField(
            model_name="salescontract",
            name="related_production_order",
        ),
        migrations.RemoveField(
            model_name="tenderneposrednitroskovi",
            name="tenant_id",
        ),
        migrations.RemoveField(
            model_name="tenderposrednitroskovi",
            name="tenant_id",
        ),
        migrations.RemoveField(
            model_name="tenderpreparation",
            name="estimated_production_time",
        ),
        migrations.RemoveField(
            model_name="tenderpreparation",
            name="payment_schedule",
        ),
        migrations.RemoveField(
            model_name="tenderpreparation",
            name="production_capacity",
        ),
        migrations.RemoveField(
            model_name="tenderpreparation",
            name="project_manager",
        ),
        # Skipped removal of proposal_drawings & technical_drawings (proposal_drawings removed earlier; technical_drawings absent in stub schema).
        migrations.RemoveField(
            model_name="tenderpreparation",
            name="tenant_id",
        ),
        migrations.RemoveField(
            model_name="tenderrasclamba",
            name="tenant_id",
        ),
        migrations.RemoveField(
            model_name="workorderinput",
            name="radni_nalog",
        ),
        migrations.AddField(
            model_name="quotation",
            name="production_order_ref",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Radni nalog (ref)"
            ),
        ),
        migrations.AddField(
            model_name="salescontract",
            name="production_order_ref",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Povezani Radni Nalog referenca"
            ),
        ),
        migrations.AddField(
            model_name="tenderpreparation",
            name="proposal_drawing_refs",
            field=models.JSONField(
                blank=True,
                help_text="Popis identifikatora / naziva nacrta",
                null=True,
                verbose_name="Ponudbeni nacrti reference (list)",
            ),
        ),
        migrations.AddField(
            model_name="workorderinput",
            name="work_order_ref",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Radni nalog referenca"
            ),
        ),
        # Skip client FK alterations referencing external client_app in stub path.
        migrations.AlterField(
            model_name="quotation",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="salescontract",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        # Skip salesopportunity client FK alteration for same reason.
        migrations.AlterField(
            model_name="salesorder",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tenderpreparation",
            name="financial_analysis",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tender_preparation",
                to="financije.financialanalysis",
                verbose_name="Financijska analiza",
            ),
        ),
        migrations.AlterField(
            model_name="tenderpreparation",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Zadnje ažuriranje"),
        ),
    ]
