# Generated by Django 4.2.23 on 2025-08-04 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_client_app__postal__8c341e_idx_client_city_postal__bddf1a_idx_and_more'),
        ('prodaja', '0012_remove_projectservicetype_tenant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_lines', models.JSONField(verbose_name='Service line items')),
                ('material_lines', models.JSONField(verbose_name='Material line items')),
                (
                    'total_amount',
                    models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total amount'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('draft', 'Draft'), ('approved', 'Approved')],
                        default='draft',
                        max_length=20,
                        verbose_name='Status',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'customer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='offers',
                        to='client.clientsupplier',
                        verbose_name='Customer',
                    ),
                ),
            ],
        ),
    ]
