# Generated by Django 4.2.23 on 2025-08-18 13:57

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financije', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Naziv odjela')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis odjela')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Ime')),
                ('last_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Prezime')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('hierarchical_level', models.PositiveIntegerField(default=1, verbose_name='Hierarchical Level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                (
                    'salary_coefficient',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('1.0'), max_digits=5, verbose_name='Salary Coefficient'
                    ),
                ),
                ('onboarding_date', models.DateField(blank=True, null=True, verbose_name='Onboarding Date')),
                (
                    'onboarding_timeline',
                    models.PositiveIntegerField(blank=True, null=True, verbose_name='Onboarding Timeline (days)'),
                ),
                (
                    'employee_satisfaction',
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Employee Satisfaction'
                    ),
                ),
                (
                    'satisfaction_score',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Satisfaction Score'
                    ),
                ),
                (
                    'access_level',
                    models.CharField(
                        choices=[
                            ('Direktor', 'Direktor'),
                            ('Administrator', 'Administrator'),
                            ('Voditelj Projekta', 'Voditelj Projekta'),
                            ('Voditelj Proizvodnje', 'Voditelj Proizvodnje'),
                            ('Nabava', 'Nabava'),
                            ('Projektant', 'Projektant'),
                            ('Radnik', 'Radnik'),
                            ('Skladištar', 'Skladištar'),
                        ],
                        default='Radnik',
                        max_length=50,
                        verbose_name='Razina pristupa',
                    ),
                ),
                (
                    'department',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='ljudski_resursi.department',
                        verbose_name='Department',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ExpertiseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Expertise Level')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Expertise Level',
                'verbose_name_plural': 'Expertise Levels',
            },
        ),
        migrations.CreateModel(
            name='HierarchicalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Naziv hijerarhijskog nivoa')),
                (
                    'level',
                    models.IntegerField(
                        help_text='Niža vrijednost = viši rang, ili obrnuto, ovisno o konvenciji.',
                        verbose_name='Razina (Level)',
                    ),
                ),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis hijerarhijskog nivoa')),
                (
                    'tenant_name',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Tenant (Holding/Operativa)'),
                ),
            ],
            options={
                'verbose_name': 'Hierarchical Level',
                'verbose_name_plural': 'Hierarchical Levels',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LocationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100, unique=True, verbose_name='Naziv lokacije')),
                ('gross_minimal', models.DecimalField(decimal_places=2, default=Decimal('951.72'), max_digits=10)),
                ('net_minimal', models.DecimalField(decimal_places=2, default=Decimal('750.00'), max_digits=10)),
                ('employer_contrib_pct', models.DecimalField(decimal_places=2, default=Decimal('16.5'), max_digits=5)),
                (
                    'meal_allowance_monthly',
                    models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10),
                ),
                (
                    'housing_allowance_monthly',
                    models.DecimalField(decimal_places=2, default=Decimal('600.00'), max_digits=10),
                ),
                ('worker_share', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Naziv pozicije')),
                ('is_managerial', models.BooleanField(default=False, verbose_name='Menadžerska pozicija')),
                (
                    'department',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='ljudski_resursi.department',
                        verbose_name='Odjel',
                    ),
                ),
                (
                    'expertise_level',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='ljudski_resursi.expertiselevel',
                        verbose_name='Razina stručnosti (default)',
                    ),
                ),
                (
                    'hierarchical_level',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='positions',
                        to='ljudski_resursi.hierarchicallevel',
                        verbose_name='Hijerarhijski nivo',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Nagrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'radni_nalog_ref',
                    models.CharField(blank=True, max_length=64, null=True, verbose_name='Radni nalog Ref'),
                ),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Iznos nagrade (€)')),
                ('razlog', models.TextField(blank=True, null=True, verbose_name='Razlog nagrade')),
                ('datum_dodjele', models.DateField(auto_now_add=True, verbose_name='Datum dodjele')),
                (
                    'employee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='nagrade',
                        to='ljudski_resursi.employee',
                        verbose_name='Zaposlenik',
                    ),
                ),
                (
                    'odobrio',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='odobrene_nagrade',
                        to='ljudski_resursi.employee',
                        verbose_name='Odobrio',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Nagrada',
                'verbose_name_plural': 'Nagrade',
                'ordering': ['-datum_dodjele'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Level')),
                (
                    'department',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='job_positions',
                        to='ljudski_resursi.department',
                        verbose_name='Department',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='expertise_level',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='employees',
                to='ljudski_resursi.expertiselevel',
                verbose_name='Expertise Level',
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subordinates',
                to='ljudski_resursi.employee',
                verbose_name='Nadređeni',
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='ljudski_resursi.position',
                verbose_name='Pozicija',
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_configuration',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='financije.taxconfiguration',
                verbose_name='Tax Configuration',
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='employee_profile',
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='managed_departments',
                to='ljudski_resursi.employee',
                verbose_name='Voditelj odjela',
            ),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subdepartments',
                to='ljudski_resursi.department',
                verbose_name='Nadređeni odjel',
            ),
        ),
        migrations.CreateModel(
            name='RadnaEvaluacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_period', models.CharField(max_length=50)),
                ('datum_evaluacije', models.DateTimeField(auto_now_add=True)),
                (
                    'efikasnost',
                    models.IntegerField(
                        choices=[(1, 'Vrlo loše'), (2, 'Loše'), (3, 'Zadovoljavajuće'), (4, 'Dobro'), (5, 'Vrlo dobro')]
                    ),
                ),
                (
                    'kvaliteta_rada',
                    models.IntegerField(
                        choices=[(1, 'Vrlo loše'), (2, 'Loše'), (3, 'Zadovoljavajuće'), (4, 'Dobro'), (5, 'Vrlo dobro')]
                    ),
                ),
                (
                    'timski_rad',
                    models.IntegerField(
                        choices=[(1, 'Vrlo loše'), (2, 'Loše'), (3, 'Zadovoljavajuće'), (4, 'Dobro'), (5, 'Vrlo dobro')]
                    ),
                ),
                (
                    'inicijativa',
                    models.IntegerField(
                        choices=[(1, 'Vrlo loše'), (2, 'Loše'), (3, 'Zadovoljavajuće'), (4, 'Dobro'), (5, 'Vrlo dobro')]
                    ),
                ),
                ('broj_zavrsenih_naloga', models.IntegerField(default=0)),
                ('prosjecna_ocjena_kvalitete', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                (
                    'ukupno_sati_rada',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Ukupno sati rada'
                    ),
                ),
                ('komentar', models.TextField(blank=True)),
                ('preporuke', models.TextField(blank=True)),
                (
                    'employee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='evaluacije',
                        to='ljudski_resursi.employee',
                    ),
                ),
                (
                    'evaluator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='dane_evaluacije',
                        to='ljudski_resursi.employee',
                    ),
                ),
            ],
            options={
                'unique_together': {('employee', 'evaluation_period')},
            },
        ),
    ]
