# Generated by Django 4.2.18 on 2025-01-30 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ljudski_resursi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financije', '0003_initial'),
        ('proizvodnja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocjenakvalitete',
            name='radni_nalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocjene_kvalitete_ljudski', to='proizvodnja.radninalog'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='ljudski_resursi.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='evaluacija',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='ljudski_resursi.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ljudski_resursi.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='ljudski_resursi.employee', verbose_name='Nadređeni'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ljudski_resursi.position', verbose_name='Pozicija'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financije.taxconfiguration', verbose_name='Tax Configuration'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='ljudski_resursi.employee', verbose_name='Voditelj odjela'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdepartments', to='ljudski_resursi.department', verbose_name='Nadređeni odjel'),
        ),
    ]
