# Generated by Django 4.2.18 on 2025-02-01 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # Removed dependency on legacy 'proizvodnja' app (disabled in MVP)
    dependencies = [
        ("financije", "0005_alter_salaryaddition_evaluation_and_more"),
        (
            "ljudski_resursi",
            "0004_nagrada_radnaevaluacija_remove_evaluacija_employee_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Evaluacija",
        ),
        migrations.DeleteModel(
            name="OcjenaKvalitete",
        ),
        migrations.AddField(
            model_name="radnaevaluacija",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluacije",
                to="ljudski_resursi.employee",
            ),
        ),
        migrations.AddField(
            model_name="radnaevaluacija",
            name="evaluator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dane_evaluacije",
                to="ljudski_resursi.employee",
            ),
        ),
        migrations.AddField(
            model_name="nagrada",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nagrade",
                to="ljudski_resursi.employee",
                verbose_name="Zaposlenik",
            ),
        ),
        migrations.AddField(
            model_name="nagrada",
            name="odobrio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="odobrene_nagrade",
                to="ljudski_resursi.employee",
                verbose_name="Odobrio",
            ),
        ),
        # Replaced FK to proizvodnja.RadniNalog with simple reference field for MVP
        migrations.AddField(
            model_name="nagrada",
            name="radni_nalog_ref",
            field=models.CharField(
                max_length=64,
                null=True,
                blank=True,
                verbose_name="Radni nalog Ref",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="radnaevaluacija",
            unique_together={("employee", "evaluation_period")},
        ),
    ]
