# Generated by Django 4.2.23 on 2025-07-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ljudski_resursi', '0008_alter_department_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hierarchicallevel',
            name='tenant_id',
        ),
    ]
