# Generated by Django 4.2.23 on 2025-08-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ljudski_resursi", "0002_employee_jls"),
        ("ljudski_resursi", "0008_alter_department_id_alter_employee_id_and_more"),
    ]

    operations = []
