# Generated by Django 4.2.23 on 2025-07-27 23:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ljudski_resursi', '0009_remove_hierarchicallevel_tenant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100, unique=True, verbose_name='Naziv lokacije')),
                ('gross_minimal', models.DecimalField(decimal_places=2, default=Decimal('951.72'), max_digits=10)),
                ('net_minimal', models.DecimalField(decimal_places=2, default=Decimal('750.00'), max_digits=10)),
                ('employer_contrib_pct', models.DecimalField(decimal_places=2, default=Decimal('16.5'), max_digits=5)),
                (
                    'meal_allowance_monthly',
                    models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10),
                ),
                (
                    'housing_allowance_monthly',
                    models.DecimalField(decimal_places=2, default=Decimal('600.00'), max_digits=10),
                ),
                ('worker_share', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='radnaevaluacija',
            name='ukupno_sati_rada',
            field=models.DecimalField(
                decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Ukupno sati rada'
            ),
        ),
    ]
