# Generated by Django 4.2.23 on 2025-08-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ljudski_resursi", "0009_merge_20250821_1204"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hierarchicallevel",
            name="tenant_id",
        ),
        # radni_nalog field not present in stubbed path; skip removal.
        migrations.AddField(
            model_name="nagrada",
            name="work_order_ref",
            field=models.CharField(
                blank=True,
                help_text="Legacy work order identifier (string).",
                max_length=64,
                null=True,
                verbose_name="Radni nalog referenca",
            ),
        ),
    ]
