# Generated by Django 4.2.14 on 2025-08-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ljudski_resursi', '0010_locationconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='expertise_level',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='employees',
                to='ljudski_resursi.expertiselevel',
                verbose_name='Expertise Level',
            ),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Ime'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Prezime'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='ljudski_resursi.position',
                verbose_name='Pozicija',
            ),
        ),
    ]
