# Generated by Django 4.2.18 on 2025-01-30 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nabava', '0001_initial'),
        ('skladiste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='artikl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skladiste.artikl', verbose_name='Artikl'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='nabava.purchaseorder', verbose_name='Purchase Order'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nabava.dobavljac', verbose_name='Dobavljač'),
        ),
    ]
