# Generated by Django 4.2.18 on 2025-01-30 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nabava", "0002_initial"),
        ("skladiste", "0001_initial"),
        ("financije", "0003_initial"),
        ("proizvodnja", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="proizvodnja.radninalog",
                verbose_name="Radni Nalog",
            ),
        ),
        migrations.AddField(
            model_name="procurementrequest",
            name="procurement_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="nabava.procurementplan",
                verbose_name="Procurement Plan",
            ),
        ),
        migrations.AddField(
            model_name="narudzbenicastavka",
            name="artikl",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="skladiste.artikl",
                verbose_name="Artikl",
            ),
        ),
        migrations.AddField(
            model_name="narudzbenicastavka",
            name="narudzbenica",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stavke",
                to="nabava.narudzbenica",
                verbose_name="Narudžbenica",
            ),
        ),
        migrations.AddField(
            model_name="narudzbenica",
            name="artikli",
            field=models.ManyToManyField(
                through="nabava.NarudzbenicaStavka",
                to="skladiste.artikl",
                verbose_name="Artikli",
            ),
        ),
        migrations.AddField(
            model_name="narudzbenica",
            name="dobavljac",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.PROTECT,
                to="nabava.dobavljac",
                verbose_name="Dobavljač",
            ),
        ),
        migrations.AddField(
            model_name="narudzbenica",
            name="racun",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="narudzbenica",
                to="financije.racun",
                verbose_name="Povezani račun",
            ),
        ),
        migrations.AddField(
            model_name="dobavljac",
            name="grupa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dobavljaci",
                to="nabava.grupadobavljaca",
                verbose_name="Grupa dobavljača",
            ),
        ),
    ]
