# Generated by Django 4.2.23 on 2025-07-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nabava', '0005_alter_dobavljac_id_alter_grupadobavljaca_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupadobavljaca',
            name='tenant_id',
        ),
    ]
