# Generated by Django 4.2.23 on 2025-07-14 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("object_id", models.PositiveIntegerField()),
                ("invoiceable", models.BooleanField(default=True)),
                (
                    "division",
                    models.CharField(
                        choices=[("BRAVARIJA", "Bravarija"), ("FARBANJE", "Farbanje")],
                        default="BRAVARIJA",
                        max_length=16,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("room", "Komora"),
                            ("vehicle", "Vozilo"),
                            ("hall", "Hala"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amort_plan", models.TextField()),
                (
                    "division",
                    models.CharField(
                        choices=[("BRAVARIJA", "Bravarija"), ("FARBANJE", "Farbanje")],
                        default="BRAVARIJA",
                        max_length=16,
                    ),
                ),
                (
                    "owner_tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
