# Generated by Django 4.2.23 on 2025-08-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0004_rename_client_app__postal__8c341e_idx_client_city_postal__bddf1a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField(verbose_name='Usage date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Usage amount')),
                ('invoiceable', models.BooleanField(default=True, verbose_name='Ready for invoicing')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Soft delete flag')),
                (
                    'client',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='asset_usages',
                        to='client.clientsupplier',
                        verbose_name='Client for asset usage',
                    ),
                ),
            ],
        ),
    ]
