# Generated by Django 4.2.23 on 2025-08-18 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_merge_0003_alter_tenant_domain_0003_tenantsettings'),
        ('financije', '0001_initial'),
        ('ljudski_resursi', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='variablepayrule',
            name='expertise_level',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='ljudski_resursi.expertiselevel',
                verbose_name='Razina stručnosti',
            ),
        ),
        migrations.AddField(
            model_name='variablepayrule',
            name='position',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='ljudski_resursi.position', verbose_name='Pozicija'
            ),
        ),
        migrations.AddField(
            model_name='variablepaycalculation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ljudski_resursi.employee'),
        ),
        migrations.AddField(
            model_name='variablecostpreset',
            name='tenant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant'
            ),
        ),
        migrations.AddIndex(
            model_name='taxconfiguration',
            index=models.Index(fields=['valid_from', 'valid_to'], name='financije_t_valid_f_ae643a_idx'),
        ),
        migrations.AddIndex(
            model_name='taxconfiguration',
            index=models.Index(fields=['is_active'], name='financije_t_is_acti_fc5b71_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxconfiguration',
            constraint=models.CheckConstraint(
                check=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='valid_tax_rate'
            ),
        ),
        migrations.AddField(
            model_name='salaryaddition',
            name='evaluation',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='salary_additions',
                to='ljudski_resursi.radnaevaluacija',
            ),
        ),
        migrations.AddField(
            model_name='salaryaddition',
            name='quality_score',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='quality_score_additions',
                to='ljudski_resursi.radnaevaluacija',
            ),
        ),
        migrations.AddField(
            model_name='salaryaddition',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financije.salary'),
        ),
        migrations.AddField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='ljudski_resursi.employee', verbose_name='Zaposlenik'
            ),
        ),
        migrations.AddIndex(
            model_name='racun',
            index=models.Index(fields=['broj'], name='financije_r_broj_cddbcd_idx'),
        ),
        migrations.AddIndex(
            model_name='racun',
            index=models.Index(fields=['datum'], name='financije_r_datum_5b4679_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='related_invoice',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financije.invoice'
            ),
        ),
        migrations.AddIndex(
            model_name='overhead',
            index=models.Index(fields=['godina', 'mjesec'], name='financije_o_godina_319e82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='overhead',
            unique_together={('godina', 'mjesec')},
        ),
        migrations.AddField(
            model_name='monthlyoverhead',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='financije.overheadcategory', verbose_name='Category'
            ),
        ),
        migrations.AddIndex(
            model_name='mjesecnioverheadpregled',
            index=models.Index(fields=['godina', 'mjesec'], name='financije_m_godina_105e1d_idx'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financije.account'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='entry',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='journalitem_set', to='financije.journalentry'
            ),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Korisnik',
            ),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='financije.invoice'
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Kreirao',
            ),
        ),
        migrations.AddField(
            model_name='fixedcost',
            name='tenant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant'
            ),
        ),
        migrations.AddField(
            model_name='financijskatransakcija',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='debt',
            name='invoice',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='debts',
                to='financije.invoice',
                verbose_name='Invoice',
            ),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='bank_transaction',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cashflow_entry',
                to='financije.banktransaction',
            ),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(
                check=models.Q(('mjesec__gte', 1), ('mjesec__lte', 12)), name='valid_month_check'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('godina', 'mjesec')},
        ),
        migrations.AddField(
            model_name='breakevensnapshot',
            name='tenant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant'
            ),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['tip_transakcije'], name='financije_b_tip_tra_25ec3f_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account_number'], name='financije_b_bank_ac_03544c_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'
            ),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subaccounts',
                to='financije.account',
                verbose_name='Nadređeni konto',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='variablepayrule',
            unique_together={('position', 'expertise_level')},
        ),
        migrations.AddIndex(
            model_name='monthlyoverhead',
            index=models.Index(fields=['year', 'month', 'category'], name='financije_m_year_f983a9_idx'),
        ),
        migrations.AddIndex(
            model_name='journalitem',
            index=models.Index(fields=['debit'], name='financije_j_debit_f48f23_idx'),
        ),
        migrations.AddIndex(
            model_name='journalitem',
            index=models.Index(fields=['credit'], name='financije_j_credit_d377ae_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='financije_j_date_f6a48e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['created_at'], name='financije_j_created_601cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='financije_i_issue_d_2b7b08_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='financije_i_due_dat_47ec64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='breakevensnapshot',
            unique_together={('tenant', 'division', 'date')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='financije_a_timesta_083c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='financije_a_user_id_95ea62_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name'], name='financije_a_model_n_ec0532_idx'),
        ),
    ]
