# Generated by Django 4.2.23 on 2025-08-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financije', '0003_tax_local_rate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taxlocalrate',
            new_name='tax_local_r_tenant__646218_idx',
            old_name='tax_jls_vf_idx',
        ),
        migrations.AlterField(
            model_name='taxlocalrate',
            name='jls_code',
            field=models.CharField(help_text='RIJEKA, BAKAR, KRALJEVICA, ZAGREB, DEFAULT ...', max_length=20),
        ),
    ]
