# Generated by Django 4.2.23 on 2025-08-19 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0005_tenant_vat_fiscal_and_settings_accounts'),
        ('financije', '0004_rename_tax_jls_vf_idx_tax_local_r_tenant__646218_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='locked',
            field=models.BooleanField(default=False, help_text='Zaključana temeljnica (period zaključen)'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='journal_entries',
                to='tenants.tenant',
            ),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='cost_center',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='labels',
            field=models.JSONField(blank=True, default=list, help_text='Lista slobodnih oznaka (tagova)'),
        ),
        migrations.CreateModel(
            name='PeriodLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                (
                    'closed_by',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='period_locks', to='tenants.tenant'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Zaključan period',
                'verbose_name_plural': 'Zaključani periodi',
                'indexes': [models.Index(fields=['tenant', 'year', 'month'], name='financije_p_tenant__78ae5b_idx')],
                'unique_together': {('tenant', 'year', 'month')},
            },
        ),
    ]
