# Generated by Django 4.2.23 on 2025-08-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financije', '0005_journalentry_locked_journalentry_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='reversal_of',
            field=models.ForeignKey(
                blank=True,
                help_text='Ako je ovo reverzna temeljnica, referenca na izvornu.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='reversals',
                to='financije.journalentry',
            ),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'date'], name='financije_j_tenant__d5932b_idx'),
        ),
    ]
