# Generated by Django 4.2.18 on 2025-02-02 00:45

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financije', '0005_alter_salaryaddition_evaluation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Cost')),
                ('expected_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Expected Profit')),
                ('risk_assessment', models.TextField(blank=True, null=True, verbose_name='Risk Assessment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Analysis',
                'verbose_name_plural': 'Financial Analyses',
            },
        ),
    ]
