# Generated by Django 4.2.23 on 2025-08-19 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_vat_fiscal_and_settings_accounts'),
        ('financije', '0006_journalentry_reversal_of_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostedJournalRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=64)),
                ('kind', models.CharField(default='generic', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'entry',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='posted_ref',
                        to='financije.journalentry',
                    ),
                ),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'ref', 'kind'], name='financije_p_tenant__9af7de_idx')],
                'unique_together': {('tenant', 'ref', 'kind')},
            },
        ),
    ]
