# Generated by Django 4.2.23 on 2025-07-15 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("financije", "0009_paintprice_balancesheet_assets_alter_account_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariableCostPreset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("division", models.CharField(max_length=64, verbose_name="Divizija")),
                ("name", models.CharField(max_length=128, verbose_name="Naziv")),
                (
                    "amount_per_unit",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        verbose_name="Iznos po jedinici",
                    ),
                ),
                ("unit", models.CharField(max_length=32, verbose_name="Jedinica")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FixedCost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("division", models.CharField(max_length=64, verbose_name="Divizija")),
                ("name", models.CharField(max_length=128, verbose_name="Naziv troška")),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Iznos"),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("M", "Mjesečno"),
                            ("Q", "Kvartalno"),
                            ("Y", "Godišnje"),
                        ],
                        default="M",
                        max_length=1,
                        verbose_name="Period",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
        ),
    ]
