# Generated by Django 4.2.23 on 2025-07-15 11:06

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("financije", "0010_variablecostpreset_fixedcost"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakEvenSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("division", models.CharField(max_length=64, verbose_name="Divizija")),
                ("date", models.DateField(verbose_name="Datum")),
                (
                    "fixed_costs",
                    models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Fiksni troškovi"),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Prihod",
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Profit",
                    ),
                ),
                (
                    "break_even_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Break-even količina",
                    ),
                ),
                (
                    "status",
                    models.CharField(default="red", max_length=16, verbose_name="Status"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Break-even snimka",
                "verbose_name_plural": "Break-even snimke",
                "unique_together": {("tenant", "division", "date")},
            },
        ),
    ]
