# Generated by Django 4.2.23 on 2025-07-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financije', '0012_balancesheet_assets_alter_account_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='breakevensnapshot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='breakevensnapshot',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fixedcost',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='PaintPrice',
        ),
        migrations.RemoveField(
            model_name='variablecostpreset',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Broj fakture'),
        ),
        migrations.DeleteModel(
            name='BreakEvenSnapshot',
        ),
        migrations.DeleteModel(
            name='FixedCost',
        ),
        migrations.DeleteModel(
            name='VariableCostPreset',
        ),
    ]
