# Generated by Django 4.2.23 on 2025-08-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financije", "0003_tax_local_rate"),
        ("financije", "0009_journalitem_non_negative_and_index"),
        ("financije", "0012_balancesheet_assets_alter_account_id_and_more"),
    ]

    operations = []
