# Generated by Django 4.2.23 on 2025-08-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financije", "0013_merge_20250821_1204"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="breakevensnapshot",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="breakevensnapshot",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="fixedcost",
            name="tenant",
        ),
        migrations.DeleteModel(
            name="PaintPrice",
        ),
        migrations.RemoveField(
            model_name="variablecostpreset",
            name="tenant",
        ),
        # primka field already absent in stubbed migration history; skip removal & replacement.
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                db_index=True, max_length=100, unique=True, verbose_name="Broj fakture"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalitem",
            constraint=models.CheckConstraint(
                check=models.Q(("debit__gt", 0), ("credit__gt", 0), _negated=True),
                name="journalitem_debit_xor_credit",
            ),
        ),
        migrations.DeleteModel(
            name="BreakEvenSnapshot",
        ),
        migrations.DeleteModel(
            name="FixedCost",
        ),
        migrations.DeleteModel(
            name="VariableCostPreset",
        ),
    ]
