# Generated by Django 4.2.23 on 2025-08-04 10:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_domain'),
        ('financije', '0013_alter_breakevensnapshot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(
                decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Ukupan iznos'
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_link',
            field=models.URLField(blank=True, null=True, verbose_name='Stripe Link'),
        ),
        migrations.CreateModel(
            name='VariableCostPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=64, verbose_name='Divizija')),
                ('name', models.CharField(max_length=128, verbose_name='Naziv')),
                (
                    'amount_per_unit',
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Iznos po jedinici'),
                ),
                ('unit', models.CharField(max_length=32, verbose_name='Jedinica')),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=64, verbose_name='Divizija')),
                ('name', models.CharField(max_length=128, verbose_name='Naziv troška')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Iznos')),
                (
                    'period',
                    models.CharField(
                        choices=[('M', 'Mjesečno'), ('Q', 'Kvartalno'), ('Y', 'Godišnje')],
                        default='M',
                        max_length=1,
                        verbose_name='Period',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='BreakEvenSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=64, verbose_name='Divizija')),
                ('date', models.DateField(verbose_name='Datum')),
                ('fixed_costs', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Fiksni troškovi')),
                (
                    'revenue',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Prihod'
                    ),
                ),
                (
                    'profit',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Profit'
                    ),
                ),
                (
                    'break_even_qty',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Break-even količina'
                    ),
                ),
                ('status', models.CharField(default='red', max_length=16, verbose_name='Status')),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Break-even snimka',
                'verbose_name_plural': 'Break-even snimke',
                'unique_together': {('tenant', 'division', 'date')},
            },
        ),
    ]
