# Generated by Django 4.2.23 on 2025-08-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_tenant_vat_fiscal_and_settings_accounts"),
        ("financije", "0014_alter_breakevensnapshot_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="tenants.tenant",
                verbose_name="Tenant",
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_transactions",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_flows",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="tenants.tenant",
                verbose_name="Tenant",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reversal_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversals",
                to="financije.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_entries",
                to="tenants.tenant",
                verbose_name="Tenant",
            ),
        ),
        migrations.AddField(
            model_name="journalitem",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_items",
                to="tenants.tenant",
                verbose_name="Tenant",
            ),
        ),
        migrations.AddField(
            model_name="racun",
            name="primka_ref",
            field=models.CharField(
                blank=True,
                help_text="Legacy skladiste.Primka identifier (string copy).",
                max_length=50,
                null=True,
                verbose_name="Primka ref",
            ),
        ),
        migrations.AddField(
            model_name="taxconfiguration",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_configurations",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="number",
            field=models.CharField(max_length=20, verbose_name="Broj konta"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["idempotency_key"], name="financije_j_idempot_b06f96_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["tenant", "date"], name="financije_j_tenant__d5932b_idx"),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("tenant", "number"), name="uniq_account_tenant_number"
            ),
        ),
    ]
