# Generated by Django 4.2.23 on 2025-08-22 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_tenant_vat_fiscal_and_settings_accounts"),
        ("financije", "0015_account_tenant_banktransaction_tenant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodClose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_closes",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Period close",
                "verbose_name_plural": "Period closes",
                "indexes": [
                    models.Index(
                        fields=["tenant", "year", "month"], name="financije_p_tenant__cfe7fa_idx"
                    )
                ],
                "unique_together": {("tenant", "year", "month")},
            },
        ),
    ]
