# Generated by Django 4.2.23 on 2025-08-19 12:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_tenant_vat_fiscal_and_settings_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                (
                    'item_type',
                    models.CharField(
                        choices=[
                            ('material', 'Material'),
                            ('consumable', 'Consumable'),
                            ('paint', 'Paint'),
                            ('semi', 'Semi-finished'),
                            ('service', 'Service'),
                        ],
                        max_length=20,
                    ),
                ),
                ('has_lots', models.BooleanField(default=False)),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True)),
                ('track_length', models.BooleanField(default=False)),
                ('direct_expense_account', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(max_length=40)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('attrs', models.JSONField(blank=True, default=dict)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
            options={
                'unique_together': {('item', 'lot_code')},
            },
        ),
        migrations.CreateModel(
            name='UoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('ratio_to_base', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                (
                    'type',
                    models.CharField(
                        choices=[('bin', 'Bin'), ('staging', 'Staging'), ('wip', 'WIP'), ('scrap', 'Scrap')],
                        default='bin',
                        max_length=10,
                    ),
                ),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='uom_base',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='base_items', to='inventory.uom'
            ),
        ),
        migrations.CreateModel(
            name='StockQuant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('cost_per_uom', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
                (
                    'lot',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stocklot'
                    ),
                ),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('item', 'warehouse', 'location', 'lot')},
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('qty', models.DecimalField(decimal_places=6, max_digits=18)),
                ('ref', models.CharField(max_length=60)),
                ('price_unit', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('value', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('state', models.CharField(default='done', max_length=12)),
                (
                    'dst',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='moves_in',
                        to='inventory.location',
                    ),
                ),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                (
                    'lot',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklot'
                    ),
                ),
                (
                    'src',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='moves_out',
                        to='inventory.location',
                    ),
                ),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.uom')),
            ],
            options={
                'indexes': [models.Index(fields=['ref', 'tenant'], name='inventory_s_ref_980e2b_idx')],
            },
        ),
    ]
