# Generated by Django 4.2.23 on 2025-08-19 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='open', max_length=20)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='stockmove',
            name='kind',
            field=models.CharField(default='generic', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='stockmove',
            constraint=models.UniqueConstraint(fields=('tenant', 'ref'), name='inventory_unique_ref_per_tenant'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='work_order',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='stock_moves',
                to='inventory.workorder',
            ),
        ),
    ]
