# Generated by Django 4.2.23 on 2025-08-19 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_workorder_stockmove_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmove',
            name='item',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item'
            ),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='uom',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.uom'
            ),
        ),
        migrations.CreateModel(
            name='WorkOrderReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=6, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                (
                    'work_order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reservations',
                        to='inventory.workorder',
                    ),
                ),
            ],
            options={
                'indexes': [models.Index(fields=['work_order', 'item'], name='inventory_w_work_or_f7817b_idx')],
                'unique_together': {('work_order', 'item', 'note')},
            },
        ),
    ]
