# Generated by Django 4.2.23 on 2025-08-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmove_item_alter_stockmove_uom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_paint_component',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PaintMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_base', models.DecimalField(decimal_places=6, max_digits=18)),
                ('hardener_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('thinner_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('loss_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_mix_qty', models.DecimalField(decimal_places=6, max_digits=18)),
                ('ref', models.CharField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'base_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='paintmix_base', to='inventory.item'
                    ),
                ),
                (
                    'work_order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='paint_mixes',
                        to='inventory.workorder',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_length_m', models.DecimalField(decimal_places=6, max_digits=18)),
                ('cuts', models.JSONField(default=list)),
                ('offcuts', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ref', models.CharField(max_length=60, unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                (
                    'work_order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='cut_plans', to='inventory.workorder'
                    ),
                ),
            ],
        ),
    ]
