# Generated by Django 4.2.18 on 2025-01-30 20:18

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ljudski_resursi", "0001_initial"),
        ("skladiste", "0001_initial"),
        ("proizvodnja", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillOfMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(default="Glavni BOM", max_length=200, verbose_name="Naziv BOM-a"),
                ),
                (
                    "opis",
                    models.TextField(blank=True, null=True, verbose_name="Opis BOM-a"),
                ),
                (
                    "status",
                    models.CharField(default="draft", max_length=50, verbose_name="Status BOM-a"),
                ),
            ],
            options={
                "verbose_name": "BOM",
                "verbose_name_plural": "BOM-ovi",
            },
        ),
        migrations.CreateModel(
            name="DesignTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "predvidjeni_sati_dizajna",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        verbose_name="Predviđeni sati dizajna",
                    ),
                ),
                (
                    "utroseni_sati",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=6,
                        verbose_name="Utrošeni sati dizajna",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "U pripremi"),
                            ("in_progress", "U izradi"),
                            ("awaiting_approval", "Čeka odobrenje"),
                            ("approved", "Odobreno"),
                            ("done", "Završeno"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "datum_pocetka",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Datum početka projektiranja",
                    ),
                ),
                (
                    "datum_zavrsetka",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Datum završetka projektiranja",
                    ),
                ),
                (
                    "bom_generiran",
                    models.BooleanField(default=False, verbose_name="BOM generiran"),
                ),
                (
                    "plan_izrađen",
                    models.BooleanField(default=False, verbose_name="Dinamički plan & gantt izrađeni"),
                ),
                (
                    "napomena",
                    models.TextField(blank=True, null=True, verbose_name="Napomena / opis dizajna"),
                ),
                (
                    "revizija_dokumentacije",
                    models.PositiveIntegerField(default=0, verbose_name="Broj revizija dokumentacije"),
                ),
                (
                    "dynamic_plan",
                    models.TextField(blank=True, null=True, verbose_name="Tekstualni prikaz planova"),
                ),
                (
                    "bill_of_materials",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_task_obj",
                        to="projektiranje_app.billofmaterials",
                    ),
                ),
                (
                    "projekt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_tasks",
                        to="proizvodnja.projekt",
                        verbose_name="Projekt (iz proizvodnje)",
                    ),
                ),
                (
                    "projektant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ljudski_resursi.employee",
                        verbose_name="Projektant",
                    ),
                ),
                (
                    "tip_vozila",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="proizvodnja.tipvozila",
                        verbose_name="Tip vozila",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zadatak projektiranja",
                "verbose_name_plural": "Zadaci projektiranja",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DokumentacijaProjektiranja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="Naziv Dokumentacije"),
                ),
                (
                    "opis",
                    models.TextField(blank=True, null=True, verbose_name="Opis Dokumentacije"),
                ),
            ],
            options={
                "verbose_name": "Dokumentacija Projektiranja",
                "verbose_name_plural": "Dokumentacije Projektiranja",
            },
        ),
        migrations.CreateModel(
            name="DinamickiPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "json_gantt_data",
                    models.JSONField(blank=True, null=True, verbose_name="Gantt podaci (JSON)"),
                ),
                (
                    "pocetak_plana",
                    models.DateField(blank=True, null=True, verbose_name="Početak plana"),
                ),
                (
                    "kraj_plana",
                    models.DateField(blank=True, null=True, verbose_name="Kraj plana"),
                ),
                (
                    "napomena",
                    models.TextField(blank=True, null=True, verbose_name="Napomena"),
                ),
                (
                    "dynamic_parameters",
                    models.JSONField(blank=True, null=True, verbose_name="Parametri za plan"),
                ),
                (
                    "bom_document",
                    models.FileField(blank=True, null=True, upload_to="bom_docs/"),
                ),
                (
                    "design_task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dinamicki_plan",
                        to="projektiranje_app.designtask",
                        verbose_name="Povezani zadatak projektiranja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dinamički plan",
                "verbose_name_plural": "Dinamički planovi",
            },
        ),
        migrations.CreateModel(
            name="BOMItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kolicina",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        verbose_name="Količina",
                    ),
                ),
                (
                    "napomena",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Napomena"),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="projektiranje_app.billofmaterials",
                        verbose_name="BOM",
                    ),
                ),
                (
                    "materijal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="skladiste.materijal",
                        verbose_name="Materijal",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM stavka",
                "verbose_name_plural": "BOM stavke",
            },
        ),
        migrations.AddField(
            model_name="billofmaterials",
            name="design_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bill_of_materials_list",
                to="projektiranje_app.designtask",
                verbose_name="Design Task",
            ),
        ),
    ]
