# Generated by Django 4.2.18 on 2025-02-01 02:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proizvodnja", "0004_alter_radninalog_gantogram_and_more"),
        (
            "projektiranje_app",
            "0002_caddocument_designrevision_designsegment_dynamicplan_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="DokumentacijaProjektiranja",
        ),
        migrations.AlterModelOptions(
            name="billofmaterials",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "BOM",
                "verbose_name_plural": "BOM-ovi",
            },
        ),
        migrations.AlterModelOptions(
            name="designtask",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Dizajnerski zadatak",
                "verbose_name_plural": "Dizajnerski zadaci",
            },
        ),
        migrations.RemoveField(
            model_name="designtask",
            name="bill_of_materials",
        ),
        migrations.RemoveField(
            model_name="designtask",
            name="bom_generiran",
        ),
        migrations.RemoveField(
            model_name="designtask",
            name="dynamic_plan",
        ),
        migrations.RemoveField(
            model_name="designtask",
            name="plan_izrađen",
        ),
        migrations.RemoveField(
            model_name="designtask",
            name="revizija_dokumentacije",
        ),
        migrations.AddField(
            model_name="billofmaterials",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Datum kreiranja",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="billofmaterials",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Datum posljednje izmjene"),
        ),
        migrations.AddField(
            model_name="designtask",
            name="autocad_drawing",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="design_drawings/autocad/",
                verbose_name="AutoCAD nacrt",
            ),
        ),
        migrations.AddField(
            model_name="designtask",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Datum kreiranja",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="designtask",
            name="solidworks_drawing",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="design_drawings/solidworks/",
                verbose_name="SolidWorks nacrt",
            ),
        ),
        migrations.AddField(
            model_name="designtask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Datum posljednje izmjene"),
        ),
        migrations.AlterField(
            model_name="billofmaterials",
            name="design_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bom_list",
                to="projektiranje_app.designtask",
                verbose_name="Glavni dizajnerski zadatak",
            ),
        ),
        migrations.DeleteModel(
            name="DinamickiPlan",
        ),
        migrations.AddField(
            model_name="dynamicplan",
            name="design_segment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dynamic_plan",
                to="projektiranje_app.designsegment",
                verbose_name="Segment dizajna",
            ),
        ),
        migrations.AddField(
            model_name="dynamicplan",
            name="design_task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dynamic_plan",
                to="projektiranje_app.designtask",
                verbose_name="Dizajnerski zadatak",
            ),
        ),
        migrations.AddField(
            model_name="designsegment",
            name="design_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="segments",
                to="projektiranje_app.designtask",
                verbose_name="Glavni zadatak projektiranja",
            ),
        ),
        migrations.AddField(
            model_name="designrevision",
            name="autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autor revizije",
            ),
        ),
        migrations.AddField(
            model_name="designrevision",
            name="design_segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="projektiranje_app.designsegment",
                verbose_name="Segment dizajna",
            ),
        ),
        migrations.AddField(
            model_name="designrevision",
            name="design_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="projektiranje_app.designtask",
                verbose_name="Dizajnerski zadatak",
            ),
        ),
        migrations.AddField(
            model_name="caddocument",
            name="design_segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cad_documents",
                to="projektiranje_app.designsegment",
                verbose_name="Segment dizajna",
            ),
        ),
        migrations.AddField(
            model_name="caddocument",
            name="design_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cad_documents",
                to="projektiranje_app.designtask",
                verbose_name="Dizajnerski zadatak",
            ),
        ),
        migrations.AddField(
            model_name="billofmaterials",
            name="design_segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bom_list",
                to="projektiranje_app.designsegment",
                verbose_name="Segment dizajna",
            ),
        ),
    ]
