# Generated by Django 4.2.23 on 2025-08-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projektiranje_app", "0003_delete_dokumentacijaprojektiranja_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designtask",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
