# Generated by Django 4.2.18 on 2025-01-30 20:18

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ljudski_resursi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skladiste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angazman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sati_rada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('datum_angazmana', models.DateField(default=django.utils.timezone.now)),
                ('je_dodatni', models.BooleanField(default=False)),
                ('razlog', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ZAVRSEN', 'Završeno'), ('U_TIJEKU', 'U tijeku')], default='U_TIJEKU', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DodatniAngazman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sati_rada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='GrupaPoslova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('naziv', models.CharField(max_length=255, unique=True, verbose_name='Naziv grupe poslova')),
                ('opis', models.TextField(blank=True, null=True, verbose_name='Opis grupe poslova')),
            ],
            options={
                'verbose_name': 'Grupa Poslova',
                'verbose_name_plural': 'Grupe Poslova',
                'ordering': ['naziv'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyWorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Nagrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('iznos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('razlog', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notifikacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('poruka', models.TextField()),
                ('procitano', models.BooleanField(default=False)),
                ('datum_stvaranja', models.DateTimeField(default=django.utils.timezone.now)),
                ('prioritet', models.CharField(choices=[('Visok', 'Visok'), ('Srednji', 'Srednji'), ('Nizak', 'Nizak')], default='Nizak', max_length=20)),
                ('tip', models.CharField(choices=[('Informacija', 'Informacija'), ('Upozorenje', 'Upozorenje'), ('Greška', 'Greška'), ('Nagrada', 'Nagrada')], default='Informacija', max_length=50)),
            ],
            options={
                'ordering': ['-datum_stvaranja'],
            },
        ),
        migrations.CreateModel(
            name='OcjenaKvalitete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('razina', models.CharField(choices=[('Voditelj', 'Voditelj'), ('Direktor', 'Direktor'), ('Neovisan', 'Neovisan')], max_length=20)),
                ('ocjena', models.PositiveIntegerField(choices=[(1, 'Vrlo loše'), (2, 'Loše'), (3, 'Zadovoljavajuće'), (4, 'Dobro'), (5, 'Vrlo dobro')])),
                ('komentar', models.TextField(blank=True, null=True)),
                ('slike', models.ImageField(blank=True, null=True, upload_to='ocjene/slike/')),
                ('video', models.FileField(blank=True, help_text='Podržani formati: mp4, avi, mkv.', null=True, upload_to='ocjene/videozapisi/')),
                ('tezinski_faktor', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='PovijestPromjena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('object_id', models.PositiveIntegerField()),
                ('promjene', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProizvodniResurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255, verbose_name='Naziv resursa')),
                ('tip', models.CharField(choices=[('materijal', 'Materijal'), ('alat', 'Alat'), ('radna_linija', 'Radna linija/stroj')], default='radna_linija', max_length=100)),
                ('opis', models.TextField(blank=True, null=True, verbose_name='Opis resursa')),
                ('dostupnost', models.BooleanField(default=True, verbose_name='Dostupnost')),
                ('kolicina', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Proizvodni Resurs',
                'verbose_name_plural': 'Proizvodni Resursi',
                'ordering': ['naziv'],
            },
        ),
        migrations.CreateModel(
            name='Proizvodnja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('naziv', models.CharField(max_length=255, verbose_name='Naziv Proizvodnje')),
                ('opis', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('datum_pocetka', models.DateField(blank=True, null=True, verbose_name='Datum Početka')),
                ('datum_zavrsetka', models.DateField(blank=True, null=True, verbose_name='Datum Završetka')),
                ('status', models.CharField(choices=[('planirano', 'Planirano'), ('u_progresu', 'U progresu'), ('zavrseno', 'Završeno')], default='planirano', max_length=50, verbose_name='Status Proizvodnje')),
            ],
            options={
                'verbose_name': 'Proizvodnja',
                'verbose_name_plural': 'Proizvodnje',
                'ordering': ['-datum_pocetka'],
            },
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('naziv_projekta', models.CharField(db_index=True, max_length=255, verbose_name='Naziv projekta')),
                ('erp_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ERP ID')),
                ('opis', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('pocetak_projekta', models.DateField(blank=True, null=True, verbose_name='Datum početka')),
                ('rok_za_isporuku', models.DateField(blank=True, null=True, verbose_name='Rok za isporuku')),
                ('status', models.CharField(choices=[('OTVOREN', 'Otvoren'), ('U_TIJEKU', 'U tijeku'), ('UPOZORENJE', 'Upozorenje'), ('UGROZEN', 'Ugrožen'), ('PROBIJEN_ROK', 'Probijen rok'), ('ZAVRSENO', 'Završeno')], default='OTVOREN', max_length=20, verbose_name='Status Projekta')),
                ('ugradnja_na_lokaciji', models.BooleanField(default=False, verbose_name='Ugradnja na Lokaciji')),
                ('ručni_unos_radnih_naloga', models.BooleanField(default=False, verbose_name='Ručni Unos Radnih Naloga')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekti',
                'ordering': ['-pocetak_projekta'],
            },
        ),
        migrations.CreateModel(
            name='RadniNalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('naziv_naloga', models.CharField(db_index=True, max_length=255, verbose_name='Naziv Naloga')),
                ('tip_posla', models.CharField(choices=[('instalacija', 'Instalacija'), ('održavanje', 'Održavanje'), ('popravak', 'Popravak'), ('drugo', 'Drugo')], default='drugo', max_length=20, verbose_name='Tip Posla')),
                ('datum_pocetka', models.DateField(blank=True, null=True, verbose_name='Datum Početka')),
                ('datum_zavrsetka', models.DateField(blank=True, null=True, verbose_name='Datum Završetka')),
                ('postotak_napretka', models.PositiveIntegerField(default=0, verbose_name='Postotak Napretka')),
                ('opis', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('prioritet', models.CharField(choices=[('visok', 'Visok'), ('srednji', 'Srednji'), ('nizak', 'Nizak')], default='srednji', max_length=10, verbose_name='Prioritet')),
                ('bypass_materijala', models.BooleanField(default=False, verbose_name='Bypass Materijala')),
                ('dokumentacija_bypass', models.BooleanField(default=False, verbose_name='Dokumentacija Bypass')),
                ('status', models.CharField(choices=[('OTVOREN', 'Otvoren'), ('U_TIJEKU', 'U tijeku'), ('CEKA_OCJENU', 'Čeka ocjenu'), ('ZAVRSENO', 'Završeno')], default='OTVOREN', max_length=30, verbose_name='Status Naloga')),
                ('predvidjeno_vrijeme', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Predviđeno Vrijeme')),
                ('stvarno_vrijeme', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Stvarno Vrijeme')),
                ('broj_naloga', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('dodatne_osobe', models.ManyToManyField(blank=True, related_name='dodatni_nalozi', to='ljudski_resursi.employee', verbose_name='Dodatne Osobe')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radni_nalozi', to='ljudski_resursi.employee')),
            ],
            options={
                'verbose_name': 'Radni Nalog',
                'verbose_name_plural': 'Radni Nalozi',
                'ordering': ['-datum_pocetka'],
            },
        ),
        migrations.CreateModel(
            name='RadniNalogMaterijal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('materijal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='radni_nalozi_stavke', to='skladiste.materijal')),
                ('radni_nalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materijali_stavke', to='proizvodnja.radninalog')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPitanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('video', models.FileField(help_text='Video datoteka za pitanje.', upload_to='video_pitanja/')),
                ('opis', models.TextField(blank=True, help_text='Dodatne informacije o video pitanju.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('radni_nalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_pitanja', to='proizvodnja.radninalog')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
        ),
        migrations.CreateModel(
            name='VideoMaterijal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('naziv', models.CharField(db_index=True, max_length=255)),
                ('opis', models.TextField(blank=True)),
                ('video_file', models.FileField(upload_to='ocjene/videozapisi/')),
                ('datum_dodavanja', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('radni_nalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_materijali', to='proizvodnja.radninalog')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['-datum_dodavanja'],
            },
        ),
        migrations.CreateModel(
            name='Usteda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('predvidjeno_vrijeme', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stvarno_vrijeme', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usteda_sati', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dodatna_nagrada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('radni_nalog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usteda', to='proizvodnja.radninalog')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipVozila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('naziv', models.CharField(max_length=255, unique=True, verbose_name='Naziv tipa vozila')),
                ('opis', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('aktivan', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Tip Vozila',
                'verbose_name_plural': 'Tipovi Vozila',
                'ordering': ['naziv'],
            },
        ),
        migrations.CreateModel(
            name='TipProjekta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('naziv', models.CharField(max_length=255, unique=True, verbose_name='Naziv tipa projekta')),
                ('opis', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('aktivan', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Tip Projekta',
                'verbose_name_plural': 'Tipovi Projekata',
                'ordering': ['naziv'],
            },
        ),
        migrations.CreateModel(
            name='TemplateRadniNalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_naloga', models.CharField(max_length=255, verbose_name='Naziv Naloga')),
                ('opis_naloga', models.TextField(blank=True, null=True, verbose_name='Opis Naloga')),
                ('default_predvidjeno_vrijeme', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Predviđeno Vrijeme')),
                ('broj_izvrsenja', models.PositiveIntegerField(default=0, verbose_name='Broj Izvršenja')),
                ('akumulirani_sati', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Akumulirani Sati')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Sort Index')),
                ('grupa_posla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_nalozi', to='proizvodnja.grupaposlova', verbose_name='Grupa Poslova')),
                ('materijali', models.ManyToManyField(related_name='template_nalozi', through='proizvodnja.RadniNalogMaterijal', to='skladiste.materijal')),
                ('tip_projekta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_nalozi', to='proizvodnja.tipprojekta', verbose_name='Tip Projekta')),
                ('tip_vozila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_nalozi', to='proizvodnja.tipvozila', verbose_name='Tip Vozila')),
            ],
            options={
                'verbose_name': 'Template Radni Nalog',
                'verbose_name_plural': 'Template Radni Nalozi',
                'ordering': ['sort_index'],
            },
        ),
        migrations.AddField(
            model_name='radninalogmaterijal',
            name='template_nalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materijali_stavke', to='proizvodnja.templateradninalog'),
        ),
    ]
