# Generated by Django 4.2.18 on 2025-02-01 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektiranje_app', '0002_caddocument_designrevision_designsegment_dynamicplan_and_more'),
        ('proizvodnja', '0003_proizvodnjastatistika_remove_nagrada_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radninalog',
            name='gantogram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gantogram_radninalozi', to='projektiranje_app.dynamicplan'),
        ),
        migrations.AlterField(
            model_name='radninalog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='radninalog',
            name='linked_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkedplan_radninalozi', to='projektiranje_app.dynamicplan'),
        ),
        migrations.AlterField(
            model_name='radninalog',
            name='tehnicka_dokumentacija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radni_nalozi', to='projektiranje_app.caddocument'),
        ),
        migrations.AlterField(
            model_name='radninalog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tipprojekta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tipprojekta',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tipprojekta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tipvozila',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tipvozila',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tipvozila',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usteda',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usteda',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usteda',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='videomaterijal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='videomaterijal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='videomaterijal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='videopitanje',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='videopitanje',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='videopitanje',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Nagrada',
        ),
        migrations.AddField(
            model_name='proizvodnjastatistika',
            name='proizvodnja',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistika', to='proizvodnja.proizvodnja'),
        ),
    ]
