# Generated by Django 4.2.23 on 2025-07-15 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_clientsupplier_tenant_id"),
        ("proizvodnja", "0004_alter_radninalog_gantogram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipprojekta",
            name="tenant_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proizvodnja_tipovi",
                to="client.clientsupplier",  # Updated to reflect renamed app
                verbose_name="Tenant (Holding/Operativa)",
            ),
        ),
    ]
