# Generated by Django 4.2.23 on 2025-07-21 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "client",
            "0004_rename_client_app__postal__8c341e_idx_client_city_postal__bddf1a_idx_and_more",
        ),
        ("proizvodnja", "0005_tipprojekta_tenant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipprojekta",
            name="tenant_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proizvodnja_tipovi",
                to="client.clientsupplier",
                verbose_name="Tenant (Holding/Operativa)",
            ),
        ),
    ]
