name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: erp
          POSTGRES_PASSWORD: erp
          POSTGRES_DB: erp
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U erp" --health-interval=5s --health-timeout=5s --health-retries=5
      redis:
        image: redis:7
        ports: ["6379:6379"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black==24.8.0 ruff==0.6.9 pytest pytest-django mypy
      - name: Lint (ruff)
        run: ruff check .
      - name: Format check (black)
        run: black --check .
      - name: Type check (mypy)
        run: mypy --config-file mypy.ini
      - name: Run migrations
        env:
            DATABASE_URL: postgres://erp:erp@localhost:5432/erp
            REDIS_URL: redis://localhost:6379/0
            DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
            SECRET_KEY: dummy
            DEBUG: "False"
            DJANGO_SETTINGS_MODULE: erp_system.settings.base
        run: |
          python manage.py migrate --noinput
      - name: Load minimal fixture
        env:
            DATABASE_URL: postgres://erp:erp@localhost:5432/erp
            REDIS_URL: redis://localhost:6379/0
            DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
            SECRET_KEY: dummy
            DEBUG: "False"
            DJANGO_SETTINGS_MODULE: erp_system.settings.base
        run: |
          if [ -f erp_system/fixtures/minimal.json ]; then python manage.py loaddata erp_system/fixtures/minimal.json; else echo "No minimal.json fixture present, skipping."; fi
      - name: Run tests
        env:
            DATABASE_URL: postgres://erp:erp@localhost:5432/erp
            REDIS_URL: redis://localhost:6379/0
            DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
            SECRET_KEY: dummy
            DEBUG: "False"
            DJANGO_SETTINGS_MODULE: erp_system.settings.test
        run: |
          pytest --cov=prodaja --cov=erp_system --cov-report=xml -q
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
      - name: Upload PDFs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: "**/*.pdf"

  docker:
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/${{ github.repository }}:latest
